
POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
  "name": "Joana",
  "email": "joana@j.com"
}

###
POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
  "client_id": "fdcdd1bf-8117-4fdc-868b-5d5cb5f41c68"
}

###
POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
  "account_id_from": "0387bad2-0504-4789-baa9-c4a3a59a6a57 ",
  "amount": 10,
  "account_id_to": "fdcdd1bf-8117-4fdc-868b-5d5cb5f41c68"
}