
POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john@j.com"
}

###
POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
  "client_id": "9054c2f1-949c-46be-a16a-4b836ad3cfd3"
}

###
POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
  "account_id_from": "940c2068-6df2-4149-ad5e-ca1dad93bf45",
  "amount": 100,
  "account_id_to": "9054c2f1-949c-46be-a16a-4b836ad3cfd3"
}